### ISSUE TITLE
Cannot find module '@aws-sdk/client-dynamodb'

### ISSUE THREAD

**Issue by Mattensor** [shelfio/jest-dynamodb#111]
Hey there

I'm running shelf on my CI, "github actions"

I get the following error below. Do I need both  "@aws-sdk/client-dynamodb" & "aws-sdk" installed 🤔 I just have aws-sdk installed as a peer dep. I missing something here?

Thank you

Versions
- Java 11
- Node 14
- aws-sdk as a peer dependency

```
Error: Jest: Got error running globalSetup - /home/runner/work/api/api/node_modules/@shelf/jest-dynamodb/setup.js, reason: Cannot find module '@aws-sdk/client-dynamodb'
Require stack:
- /home/runner/work/api/api/node_modules/@shelf/jest-dynamodb/setup.js
- /home/runner/work/api/api/node_modules/jest-util/build/requireOrImportModule.js
- /home/runner/work/api/api/node_modules/jest-util/build/index.js
- /home/runner/work/api/api/node_modules/@jest/core/build/cli/index.js
- /home/runner/work/api/api/node_modules/@jest/core/build/jest.js
- /home/runner/work/api/api/node_modules/jest-cli/build/cli/index.js
- /home/runner/work/api/api/node_modules/jest-cli/bin/jest.js
- /home/runner/work/api/api/node_modules/jest/bin/jest.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/runner/work/api/api/node_modules/@shelf/jest-dynamodb/setup.js:3:20)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object.newLoader (/home/runner/work/api/api/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
npm ERR! Test failed.  See above for more details.
Error: Process completed with exit code 1.
```

![image](https://user-images.githubusercontent.com/10224902/133918284-2aa7f2ef-5419-4ba3-915d-faf52a813515.png)

**Comment by vladgolubev** [comment]
Yes, you need to have `@aws-sdk/client-dynamodb` installed instead of `aws-sdk`

See https://github.com/shelfio/jest-dynamodb/releases/tag/v2.0.0 release notes

**Comment by Mattensor** [comment]
Thanks
