### ISSUE TITLE
Jest 28: Class extends value #<Object> is not a constructor or null

### ISSUE THREAD

**Issue by domdomegg** [shelfio/jest-dynamodb#129]
// Self-answering question to help others with the same issue

After updating to Jest 28, when running tests I am getting the error:

```
  ● Test suite failed to run

    TypeError: Class extends value #<Object> is not a constructor or null

      at Object.<anonymous> (node_modules/@shelf/jest-dynamodb/environment.js:5:52)
      at Object.newLoader (node_modules/pirates/lib/index.js:141:7)
      at ScriptTransformer.requireAndTranspileModule (node_modules/@jest/transform/build/ScriptTransformer.js:895:66)
```

This appears to be related to `DynamoDBEnvironment` extending `NodeEnvironment` (from `jest-environment-node`).

**Comment by domdomegg** [comment]
To fix this, set `testEnvironment` to `node` e.g.:

```json
{
  "name": "my-package",
  "dependencies": {
    "aws-sdk": "^2.1125.0",
  },
  "devDependencies": {
    "@shelf/jest-dynamodb": "^2.2.3",
    "jest": "^28.0.3",
    "serverless": "^3.16.0",
  },
  "scripts": {
    "test": "jest",
  },
  "jest": {
    "preset": "@shelf/jest-dynamodb",
    "testEnvironment": "node"
  }
}
```
