### ISSUE TITLE
TypeError at environment.js

### ISSUE THREAD

**Issue by AdrDSB** [shelfio/jest-dynamodb#130]
Hi,

installed jest-dynamodb and my tests fail due to the following error: 
```
TypeError: Class extends value #<Object> is not a constructor or null
      at Object.<anonymous> (node_modules/@shelf/jest-dynamodb/environment.js:5:52)
      at Object.newLoader (node_modules/pirates/lib/index.js:141:7)
      at ScriptTransformer.requireAndTranspileModule (node_modules/@jest/transform/build/ScriptTransformer.js:890:66)
```
So this should be about `class DynamoDBEnvironment extends NodeEnvironment`. Could this be due to a circular dependency? (see [this](https://stackoverflow.com/questions/49854811/class-extends-value-object-is-not-a-constructor-or-null))

**Comment by claudioscheer** [comment]
Hi, @AdrDSB.

Take a look at #129. Hope it helps you.

**Comment by AdrDSB** [comment]
Thanks for the reply @claudioscheer,
however, I switched to dynalite.
