### ISSUE TITLE
Error: A JNI error has occurred, please check your installation and try again

### ISSUE THREAD

**Issue by techuila** [shelfio/jest-dynamodb#159]
Could not run jest when added @shelf/jest-dynamodb as preset in the `jest.config.js` file. 

Error:
```
Determining test suites to run...Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/jetty/server/handler/AbstractHandler
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:650)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:632)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.server.handler.AbstractHandler
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 19 more
```

**Package Versions**
```
"@shelf/jest-dynamodb": "^2.2.4"
"jest": "^26.4.2",
"ts-jest": "^26.2.0"
```

**Comment by vladgolubev** [comment]
Run export DEBUG='dynamodb-local' command

Look for Checking for DynamoDB-Local log message

![CleanShot 2022-07-19 at 22 55 32](https://user-images.githubusercontent.com/3817380/179846740-f459c238-7bf2-4562-951f-adfd7364cc8d.png)

Run rm -R /var/folders/vq/0j4hndgs5ljcvtx59mmnnmb80000gn/T/dynamodb-local (paste the path from the log message) to remove invalid version of dynamodb-local

Re-run your tests

**Comment by techuila** [comment]
@vladgolubev it worked! Thanks!
