### ISSUE TITLE
TimeToLiveSpecification support

### ISSUE THREAD

**Issue by domdomegg** [shelfio/jest-dynamodb#62]
Currently ParamValidator fails if a TimeToLiveSpecification is provided in the table properties.

Expected behaviour: TimeToLiveSpecification does not cause it to fail, and ideally would be used by the db

```
UnexpectedParameter: Unexpected key 'TimeToLiveSpecification' found in params
    at ParamValidator.fail (node_modules\aws-sdk\lib\param_validator.js:50:37)
    at ParamValidator.validateStructure (node_modules\aws-sdk\lib\param_validator.js:77:14)
    at ParamValidator.validateMember (node_modules\aws-sdk\lib\param_validator.js:88:21)
    at ParamValidator.validate (node_modules\aws-sdk\lib\param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (node_modules\aws-sdk\lib\event_listeners.js:126:42)
    at Request.callListeners (node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at callNextListener (node_modules\aws-sdk\lib\sequential_executor.js:96:12)
    at node_modules\aws-sdk\lib\event_listeners.js:86:9
    at finish (node_modules\aws-sdk\lib\config.js:357:7)
    at node_modules\aws-sdk\lib\config.js:375:9
    at SharedIniFileCredentials.get (node_modules\aws-sdk\lib\credentials.js:127:7)
    at getAsyncCredentials (node_modules\aws-sdk\lib\config.js:369:24)
    at Config.getCredentials (node_modules\aws-sdk\lib\config.js:389:9)
    at Request.VALIDATE_CREDENTIALS (node_modules\aws-sdk\lib\event_listeners.js:81:26)
    at Request.callListeners (node_modules\aws-sdk\lib\sequential_executor.js:102:18)
    at Request.emit (node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (node_modules\aws-sdk\lib\state_machine.js:14:12)
    at Request.runTo (node_modules\aws-sdk\lib\request.js:403:15)
    at node_modules\aws-sdk\lib\request.js:792:12
    at new Promise (<anonymous>)
    at Request.promise (node_modules\aws-sdk\lib\request.js:778:12)
    at Promise.all.tables.map.table (node_modules\@shelf\jest-dynamodb\setup.js:27:70)
    at Array.map (<anonymous>)
    at createTables (node_modules\@shelf\jest-dynamodb\setup.js:27:29)
    at module.exports (node_modules\@shelf\jest-dynamodb\setup.js:23:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by vladgolubev** [comment]
Hey @domdomegg what version of `aws-sdk` are you using? Looks like old version of `aws-sdk` which doesn't support this property yet

**Comment by domdomegg** [comment]
That log was from aws-sdk `2.548.0`. Still seems to happen with the current latest (`2.551.0`)

I've got a branch here that reliably recreates this error:

https://github.com/domdomegg/shrolebot/tree/jest-dynamodb-issue-62

Github actions log: https://github.com/domdomegg/shrolebot/runs/263908121

```
2019-10-17T12:30:01.5429650Z UnexpectedParameter: Unexpected key 'TimeToLiveSpecification' found in params
2019-10-17T12:30:01.5431858Z     at ParamValidator.fail (/home/runner/work/shrolebot/shrolebot/node_modules/aws-sdk/lib/param_validator.js:50:37)
2019-10-17T12:30:01.5433823Z     at ParamValidator.validateStructure (/home/runner/work/shrolebot/shrolebot/node_modules/aws-sdk/lib/param_validator.js:77:14)
2019-10-17T12:30:01.5435370Z     at ParamValidator.validateMember (/home/runner/work/shrolebot/shrolebot/node_modules/aws-sdk/lib/param_validator.js:88:21)
2019-10-17T12:30:01.5436779Z     at ParamValidator.validate (/home/runner/work/shrolebot/shrolebot/node_modules/aws-sdk/lib/param_validator.js:34:10)
2019-10-17T12:30:01.5438193Z     at Request.VALIDATE_PARAMETERS (/home/runner/work/shrolebot/shrolebot/node_modules/aws-sdk/lib/event_listeners.js:126:42)
2019-10-17T12:30:01.5439628Z     at Request.callListeners (/home/runner/work/shrolebot/shrolebot/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
2019-10-17T12:30:01.5444581Z     at callNextListener (/home/runner/work/shrolebot/shrolebot/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
2019-10-17T12:30:01.5446072Z     at /home/runner/work/shrolebot/shrolebot/node_modules/aws-sdk/lib/event_listeners.js:86:9
2019-10-17T12:30:01.5447306Z     at finish (/home/runner/work/shrolebot/shrolebot/node_modules/aws-sdk/lib/config.js:357:7)
2019-10-17T12:30:01.5452389Z     at /home/runner/work/shrolebot/shrolebot/node_modules/aws-sdk/lib/config.js:399:9
2019-10-17T12:30:01.5453915Z     at Object.<anonymous> (/home/runner/work/shrolebot/shrolebot/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:111:13)
2019-10-17T12:30:01.5454881Z     at Object.arrayEach (/home/runner/work/shrolebot/shrolebot/node_modules/aws-sdk/lib/util.js:516:32)
2019-10-17T12:30:01.5455859Z     at resolveNext (/home/runner/work/shrolebot/shrolebot/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:110:20)
2019-10-17T12:30:01.5456874Z     at /home/runner/work/shrolebot/shrolebot/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:126:13
2019-10-17T12:30:01.5457847Z     at EnvironmentCredentials.get (/home/runner/work/shrolebot/shrolebot/node_modules/aws-sdk/lib/credentials.js:127:7)
2019-10-17T12:30:01.5458847Z     at resolveNext (/home/runner/work/shrolebot/shrolebot/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:125:17)
2019-10-17T12:30:01.5459985Z     at CredentialProviderChain.resolve (/home/runner/work/shrolebot/shrolebot/node_modules/aws-sdk/lib/credentials/credential_provider_chain.js:133:7)
2019-10-17T12:30:01.5460999Z     at Config.getCredentials (/home/runner/work/shrolebot/shrolebot/node_modules/aws-sdk/lib/config.js:394:31)
2019-10-17T12:30:01.5462014Z     at Request.VALIDATE_CREDENTIALS (/home/runner/work/shrolebot/shrolebot/node_modules/aws-sdk/lib/event_listeners.js:81:26)
2019-10-17T12:30:01.5463388Z     at Request.callListeners (/home/runner/work/shrolebot/shrolebot/node_modules/aws-sdk/lib/sequential_executor.js:102:18)
2019-10-17T12:30:01.5464381Z     at Request.emit (/home/runner/work/shrolebot/shrolebot/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
2019-10-17T12:30:01.5465283Z     at Request.emit (/home/runner/work/shrolebot/shrolebot/node_modules/aws-sdk/lib/request.js:683:14)
2019-10-17T12:30:01.5466220Z     at Request.transition (/home/runner/work/shrolebot/shrolebot/node_modules/aws-sdk/lib/request.js:22:10)
2019-10-17T12:30:01.5467169Z     at AcceptorStateMachine.runTo (/home/runner/work/shrolebot/shrolebot/node_modules/aws-sdk/lib/state_machine.js:14:12)
2019-10-17T12:30:01.5468493Z     at Request.runTo (/home/runner/work/shrolebot/shrolebot/node_modules/aws-sdk/lib/request.js:403:15)
2019-10-17T12:30:01.5469371Z     at /home/runner/work/shrolebot/shrolebot/node_modules/aws-sdk/lib/request.js:792:12
2019-10-17T12:30:01.5469829Z     at new Promise (<anonymous>)
2019-10-17T12:30:01.5470610Z     at Request.promise (/home/runner/work/shrolebot/shrolebot/node_modules/aws-sdk/lib/request.js:778:12)
2019-10-17T12:30:01.5471725Z     at Promise.all.tables.map.table (/home/runner/work/shrolebot/shrolebot/node_modules/@shelf/jest-dynamodb/setup.js:27:70)
2019-10-17T12:30:01.5472257Z     at Array.map (<anonymous>)
2019-10-17T12:30:01.5473422Z     at createTables (/home/runner/work/shrolebot/shrolebot/node_modules/@shelf/jest-dynamodb/setup.js:27:29)
2019-10-17T12:30:01.5474357Z     at module.exports (/home/runner/work/shrolebot/shrolebot/node_modules/@shelf/jest-dynamodb/setup.js:23:9)
2019-10-17T12:30:01.5474987Z     at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by vladgolubev** [comment]
Looks like an upstream issue with AWS. See https://github.com/aws/aws-sdk-js/issues/1527#issuecomment-305026722
