### ISSUE TITLE
Prevents other aws-sdk classes from working

### ISSUE THREAD

**Issue by alan-cooney** [shelfio/jest-dynamodb#85]
Simply by setting the following in jest config, all other AWS services (e.g. Secrets Manager) stop working:

### Config used

```json
{ "preset": "@shelf/jest-dynamodb" }
```

### Any AWS service usage

```typescript
import { SecretsManager } from 'aws-sdk';

export default async function getSecret() {
  const secretsManager = new SecretsManager();
  const res = await secretsManager
    .getSecretValue({
      SecretId: "name",
    })
    .promise();
  return res;
}
```

### Error message with Secrets Manager

```shell
UnrecognizedClientException: The security token included in the request is invalid.

      at Request.extractError (node_modules/aws-sdk/lib/protocol/json.js:51:27)
      at Request.callListeners (node_modules/aws-sdk/lib/sequential_executor.js:106:20)
      at Request.emit (node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (node_modules/aws-sdk/lib/request.js:688:14)
      at Request.transition (node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (node_modules/aws-sdk/lib/state_machine.js:14:12)
      at node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (node_modules/aws-sdk/lib/request.js:690:12)
      at Request.callListeners (node_modules/aws-sdk/lib/sequential_executor.js:116:18)
```

**Comment by aisamu** [comment]
One thing to look for is that some important env vars are being overwritten:

https://github.com/shelfio/jest-dynamodb/blob/df33676816f3829a2121a4b66e02cce5de7270f6/setup.js#L8-L9

In our case, we're running a path that just checks for the var's existence: 
```js
if(typeof process.env.AWS_ACCESS_KEY_ID !== 'undefined')
  process.env.AWS_ACCESS_KEY_ID = 'access-key';
if(typeof process.env.AWS_SECRET_ACCESS_KEY !== 'undefined')
  process.env.AWS_SECRET_ACCESS_KEY = 'secret-key';
```

**Comment by ebisbe** [comment]
@aisamu I see in your repo that you ended removing the credentials. It's happening to me the same. I set my own credentials later and somehow it messes everything. Like in your repo deleting both lines lets works everything else. 
That's your final solution?

**Comment by aisamu** [comment]
@ebisbe yup, the final solution was just to prevent any kind of env tampering whatsoever. 
You may run into issues if you're running into environments that have zero credentials, but you can then locally reintroduce the phony values into the env before invoking `jest`.

**Comment by ebisbe** [comment]
@aisamu I found an easy and simple fix that let me work with the module without having to fork it. So I was searching how this module and https://github.com/freshollie/jest-dynalite works.
The thing is that during the set up process of jest they initialize the aws-sdk with the fake credentials. Then if you override the keys the aws-sdk has already keys so it does nothing. In my case I set up the keys in a later stage ( on each test ) so it's all configured in the code. 

What you need to do is call
```
AWS.config.update({
    accessKeyId: process.env.AWS_ACCESS_KEY_ID,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
    region: process.env.AWS_REGION
  })
``` 
when calling the services. I have a utility method where that stuff happens so I can centralise all configs for AWS services and I can have it in one place.

**Comment by sibelius** [comment]
can we just remove those lines?

**Comment by ebisbe** [comment]
> @ebisbe I don't see how your code could possibly work, this package ovverrides the env variables, if you ask for them at a later stage they will be written.
> 
> It's really bad what this library is doing.
> 
> I think the only fix is to remove those lines or better, as suggested above to check if those variables are not present and set them only in that case.
> 
> Is there a way otherwise to disable this jest-dynamodb?
> 
> What I want to do is test for real integration for end2end tests, I can't get all my tests running only on localdb

@aterreno I think it's all explained there... When you initialise your AWS services use 
```
AWS.config.update({
    accessKeyId: process.env.AWS_ACCESS_KEY_ID,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
    region: process.env.AWS_REGION
  })
  ```
  to set the proper AWS keys. You will override everything that has been set prior to this point.

**Comment by aterreno** [comment]
@ebisbe if the env variables are written I don't have the value anymore, it's lost. 

I've found a way, a little hacky but it works and I have more control. 

So you can 'override' the globalSetup in jest, 

```javascript    
globalSetup: resolve(__dirname, './setup.js'),
``` 

inside jest.config.js 

then I copied setup.js from the main folder of this repo. 

I've set a env variable, if it's unit testing I exec the setup as-is, if not I just do: 

```javascript 
else {
        const dynamoDB = new DynamoDB({
            region: process.env.AWS_DEFAULT_REGION,
        });

        global.__DYNAMODB_CLIENT__ = dynamoDB;
    }
```

I have to say this lib messes with process.env and also uses a global... 

I hope this heps others in the same situation

**Comment by ebisbe** [comment]
> if the env variables are written I don't have the value anymore, it's lost.

Oh, yes. It works for me because I load them manually later from `dotenv`. So that's why I over ride it

**Comment by vladgolubev** [comment]
Fixed in https://github.com/shelfio/jest-dynamodb/releases/tag/v2.2.3
